//! Summary sink trait and conversation summary type.
//!
//! Mirrors the `AuditSink` / `EventSink` pattern: the trait lives in
//! `freebird-traits` so the runtime can depend on it without pulling in
//! a concrete storage backend (e.g. `freebird-memory`).

use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use crate::id::SessionId;
use crate::memory::MemoryError;

/// A compressed summary of older conversation turns.
///
/// Generated by the summarization subsystem when the conversation approaches
/// the model's context window limit. Turns `0..=summarized_through_turn` are
/// replaced with this summary during message building.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ConversationSummary {
    /// Which session this summary belongs to.
    pub session_id: SessionId,
    /// The generated summary text (injected as a user message when building
    /// the completion request).
    pub text: String,
    /// Index of the last turn that was summarized (inclusive).
    /// Turns `0..=summarized_through_turn` are skipped during message building;
    /// turns after this index are included in full.
    pub summarized_through_turn: usize,
    /// Approximate token count of the original content that was compressed.
    pub original_token_estimate: usize,
    /// When the summary was generated.
    pub generated_at: DateTime<Utc>,
}

/// Persistent storage for conversation summaries.
///
/// One summary per session. Re-summarization replaces the previous summary.
/// Implementations are expected to be backed by the same encrypted database
/// as conversation events and audit logs.
#[async_trait]
pub trait SummarySink: Send + Sync + 'static {
    /// Load the summary for a session, if one exists.
    async fn load(
        &self,
        session_id: &SessionId,
    ) -> Result<Option<ConversationSummary>, MemoryError>;

    /// Save (upsert) a summary for a session.
    async fn save(&self, summary: &ConversationSummary) -> Result<(), MemoryError>;

    /// Delete the summary for a session (e.g., on session delete).
    async fn delete(&self, session_id: &SessionId) -> Result<(), MemoryError>;
}
